/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_final;

/**
 *
 * @author leoxi
 */
public class calculadora_interface extends javax.swing.JFrame {

    /**
     * Creates new form calculadora_interface
     */
    public calculadora_interface() {
        initComponents();
    }
    String numero1 = "";
    String numero2 = "";
    int contador=0;
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num2 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sumar1 = new javax.swing.JButton();
        raiz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num2.setBackground(new java.awt.Color(153, 255, 153));
        num2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num2.setForeground(new java.awt.Color(0, 0, 204));
        num2.setText("2");
        num2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 30, 30));

        num1.setBackground(new java.awt.Color(153, 255, 153));
        num1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num1.setForeground(new java.awt.Color(0, 0, 204));
        num1.setText("1");
        num1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 30));

        num3.setBackground(new java.awt.Color(153, 255, 153));
        num3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num3.setForeground(new java.awt.Color(0, 0, 204));
        num3.setText("3");
        num3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 30, 30));

        num5.setBackground(new java.awt.Color(153, 255, 153));
        num5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num5.setForeground(new java.awt.Color(0, 0, 204));
        num5.setText("5");
        num5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 30, 30));

        num4.setBackground(new java.awt.Color(153, 255, 153));
        num4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num4.setForeground(new java.awt.Color(0, 0, 204));
        num4.setText("4");
        num4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 30, 30));

        num6.setBackground(new java.awt.Color(153, 255, 153));
        num6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num6.setForeground(new java.awt.Color(0, 0, 204));
        num6.setText("6");
        num6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 30, 30));

        num8.setBackground(new java.awt.Color(153, 255, 153));
        num8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num8.setForeground(new java.awt.Color(0, 0, 204));
        num8.setText("8");
        num8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 30, 30));

        num7.setBackground(new java.awt.Color(153, 255, 153));
        num7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num7.setForeground(new java.awt.Color(0, 0, 204));
        num7.setText("7");
        num7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 30, 30));

        num9.setBackground(new java.awt.Color(153, 255, 153));
        num9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num9.setForeground(new java.awt.Color(0, 0, 204));
        num9.setText("9");
        num9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 30, 30));

        num0.setBackground(new java.awt.Color(153, 255, 153));
        num0.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        num0.setForeground(new java.awt.Color(0, 0, 204));
        num0.setText("0");
        num0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 30, 30));

        punto.setBackground(new java.awt.Color(255, 204, 51));
        punto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        punto.setForeground(new java.awt.Color(0, 51, 255));
        punto.setText(".");
        punto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        getContentPane().add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 30, 30));

        borrar.setBackground(new java.awt.Color(255, 204, 51));
        borrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        borrar.setForeground(new java.awt.Color(0, 51, 255));
        borrar.setText("CE");
        borrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 30, 30));

        sumar.setBackground(new java.awt.Color(255, 204, 51));
        sumar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        sumar.setForeground(new java.awt.Color(0, 51, 255));
        sumar.setText("+");
        sumar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        getContentPane().add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 30));

        restar.setBackground(new java.awt.Color(255, 204, 51));
        restar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        restar.setForeground(new java.awt.Color(0, 51, 255));
        restar.setText("-");
        restar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        getContentPane().add(restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 30, 30));

        multiplicar.setBackground(new java.awt.Color(255, 204, 51));
        multiplicar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        multiplicar.setForeground(new java.awt.Color(0, 51, 255));
        multiplicar.setText("*");
        multiplicar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 30, 30));

        dividir.setBackground(new java.awt.Color(255, 204, 51));
        dividir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        dividir.setForeground(new java.awt.Color(0, 51, 255));
        dividir.setText("/");
        dividir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });
        getContentPane().add(dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 30, 30));

        resultado.setBackground(new java.awt.Color(0, 204, 204));
        resultado.setForeground(new java.awt.Color(0, 51, 255));
        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 110));

        etiqueta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, 20));

        etiqueta2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 20));

        etiqueta3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 204));
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 80));

        jLabel1.setText("CALCULADORA BASICA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        sumar1.setBackground(new java.awt.Color(255, 204, 51));
        sumar1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        sumar1.setForeground(new java.awt.Color(0, 51, 255));
        sumar1.setText("+");
        sumar1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        sumar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumar1ActionPerformed(evt);
            }
        });
        getContentPane().add(sumar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 30));

        raiz.setBackground(new java.awt.Color(255, 204, 51));
        raiz.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        raiz.setForeground(new java.awt.Color(0, 51, 255));
        raiz.setText("√");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        getContentPane().add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        numero1 += "1" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        numero1 += "2" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        numero1 += "3" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        numero1 += "4" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        numero1 += "5" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        numero1 += "6" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        numero1 += "7" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        numero1 += "8" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        numero1 += "9" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        numero1 += "0" ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_num0ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        numero1 += "." ;
        etiqueta3.setText(numero1);
    }//GEN-LAST:event_puntoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        numero1 = "";
        numero2 = "";
        etiqueta1.setText("");
        etiqueta2.setText("");
        etiqueta3.setText("");
        contador = 0;
    }//GEN-LAST:event_borrarActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("+");
            
        }
    }//GEN-LAST:event_sumarActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("-");
        }
    }//GEN-LAST:event_restarActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("x");
        }
    }//GEN-LAST:event_multiplicarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("/");
        }
    }//GEN-LAST:event_dividirActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
       if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("");
        }
    }//GEN-LAST:event_resultadoActionPerformed

    private void sumar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumar1ActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        if(!etiqueta3.getText().equals("") || contador != 0){
            operaciones();
            etiqueta2.setText("√");
        }
    }//GEN-LAST:event_raizActionPerformed
    void operaciones(){
        double n1,n2;
        if(!etiqueta3.getText().equals("")){
            if(contador==0){
                numero2 = numero1;
                etiqueta2.setText(numero2);
            }
            if(numero2.equals("")){
                numero2 = "0";
            }
            n1 = Double.valueOf(numero2);
            n2 = Double.valueOf(numero1);
            if(etiqueta2.getText().equals("-")){
                numero2 = String.valueOf(n1-n2);
            }
            if(etiqueta2.getText().equals("+")){
                numero2 = String.valueOf(n1+n2);
            }
            if(etiqueta2.getText().equals("x")){
                numero2 = String.valueOf(n1*n2);
            }
            if(etiqueta2.getText().equals("/")){
                numero2 = String.valueOf(n1/n2);
            }
            etiqueta3.setText("");
            numero1 = "" ;
            contador++;
            etiqueta1.setText(numero2);
        }
    
}
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new calculadora_interface().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton dividir;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton punto;
    private javax.swing.JButton raiz;
    private javax.swing.JButton restar;
    private javax.swing.JButton resultado;
    private javax.swing.JButton sumar;
    private javax.swing.JButton sumar1;
    // End of variables declaration//GEN-END:variables
}
